# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\"w\n\x04User\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x0f\n\x07Surname\x18\x02 \x01(\t\x12\x10\n\x08Username\x18\x03 \x01(\t\x12\r\n\x05\x45mail\x18\x04 \x01(\t\x12\r\n\x05Phone\x18\x05 \x01(\t\x12\x0e\n\x06Gender\x18\x06 \x01(\t\x12\x10\n\x08Password\x18\x07 \x01(\t\"/\n\x0eSignUpResponse\x12\x0c\n\x04\x43ode\x18\x01 \x01(\x03\x12\x0f\n\x07Message\x18\x02 \x01(\t25\n\x0b\x41uthService\x12&\n\nCreateUser\x12\x05.User\x1a\x0f.SignUpResponse\"\x00\x42\nZ\x08./gen/pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010./gen/pb'
  _USER._serialized_start=14
  _USER._serialized_end=133
  _SIGNUPRESPONSE._serialized_start=135
  _SIGNUPRESPONSE._serialized_end=182
  _AUTHSERVICE._serialized_start=184
  _AUTHSERVICE._serialized_end=237
# @@protoc_insertion_point(module_scope)
